# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-SNMP
version:      0.92
version_from: SNMP.pm
installdirs:  site
requires:
    Net::SNMP:                     0
    POE:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
