--- #YAML:1.0
name:                POE-Component-SNMP
version:             1.10
abstract:            ~
license:             perl
author:              
    - Rob Bloodgood <rob@exitexchange.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Net::SNMP:                     4
    POE:                           0.31
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
