--- #YAML:1.0
name:               POE-Component-SNMP
version:            1.1006
abstract:           ~
author:
    - Rob Bloodgood <rob@exitexchange.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SNMP:    0
    POE:          0.31
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
